import Header from "@/_components/Header"
import { ThemeProvider } from "next-themes"
// import { Inter } from "next/font/google"
import Footer from "@/_components/Footer"
import "./globals.css"

// const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "MovieDB - A Collection of Your Refreshment",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <body className="dark:bg-body bg-white font-[Sora] dark:text-white text-dark" >
        <ThemeProvider attribute="class">
          <Header />
          <main>
            {children}

            {/* modal content */}
            <div id="modal-root-content"/>
          </main>
          <Footer/>
        </ThemeProvider>
      </body>
    </html>
  )
}
